### ISSUE TITLE
Production settings

### ISSUE THREAD

**Issue by fproldan** [valerymelou/cookiecutter-django-gulp#87]
Hi! Thanks for this awesome cookiecutter!
I've a site running with gunicorn + nginx, and have an .env file with DJANGO_SETTINGS_MODULE=config.settings.production but it's seems django still use local.py settings.

How i can force to use production settings?

Thanks

**Comment by valerymelou** [comment]
Hi! Where did you put your .env file? Make sure to put it in the settings module just nearby common.py, local.py...

**Comment by fproldan** [comment]
Thanks for your answer.
I had the .env file in the wrong folder, moved it to config/settings folder and it's works.

Thanks

**Comment by valerymelou** [comment]
Happy to help!
